apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yttscrb.fullname" . }}-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "yttscrb.fullname" . }}-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "yttscrb.fullname" . }}-worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: {{- toYaml .Values.worker.command | nindent 12 }}
          args: {{- toYaml .Values.worker.args | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "yttscrb.fullname" . }}-config
            - secretRef:
                name: {{ .Values.app.secrets.existingSecret }}
          volumeMounts:
            - name: cookies
              mountPath: /app/cookies
              readOnly: true
      volumes:
        - name: cookies
          secret:
            secretName: {{ .Values.app.secrets.existingSecret }}
            items:
              - key: YT_DLP_COOKIES
                path: cookies.txt
            optional: true
