apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yttscrb.fullname" . }}-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "yttscrb.fullname" . }}-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "yttscrb.fullname" . }}-worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["php", "artisan", "queue:work", "redis", "--queue=default", "--sleep=1", "--tries=3", "--timeout=0"]
          envFrom:
            - configMapRef:
                name: {{ include "yttscrb.fullname" . }}-config
            - secretRef:
                name: {{ .Values.app.secrets.existingSecret }}
