apiVersion: v1
kind: Secret
metadata:
  name: yttscrb-secrets
type: Opaque
stringData:
  APP_KEY: "base64:replace-me"
  DB_PASSWORD: "replace-me"
  REDIS_PASSWORD: "replace-me"
  GROQ_API_KEY: "replace-me"
  OPENAI_API_KEY: "replace-me"
